### ISSUE TITLE
no reachable servers

### ISSUE THREAD

**Issue by jefersonf** [AkhilSharma90/golang-todo#1]
HI @AkhilSharma90 , I've been following the golang TODO project on your youtube channel. I had tried to do it my way but following every step of the video series.

The build is ok, but when running the following error comes..

```
2021/06/15 15:07:09 no reachable servers                                                                                
exit status 1 
```
So I just copied your source code to run it and the same error occurs. Could you guess what the problem is? I'm not familiar with mgo any way...

**Comment by nicholas-buscaglia** [comment]
Hi - Running into this same issue on mac. How did you resolve this?? Thanks
